### ISSUE TITLE
Archive used spools

### ISSUE THREAD

**Issue by solo2424** [Donkie/Spoolman#13]
It would be nice to retire spools once they are empty. Keep in a database to revisit if you ever want to see what you used in the past and notes you may have left with them. Being able to search (comments/notes) would be nice too. eg. if you add information like objects you printed with a certain spool, and you go back and search for that object name. It will show all the spools that were tagged with it. So you search Iron Man, and all the spools you used for iron man would show.  I am not sure how many others care about this. But I guess I like to be overly informed.  

As far as UI. Maybe a dropdown on the spool list where Actions are, that give option to View, Edit, Retire, Delete.  so you can do it right from the list screen.

**Comment by Donkie** [comment]
That's a good idea. I guess the correct term would be "Archive", not retire

Please keep issues to 1 request/bug per issue, otherwise it becomes hard to track.

Search has definitely been on my mind.

It would be hard for Spoolman to keep track of things you've printed, and be a bit out of place. It would fit better if the already existing history in moonraker/mainsail kept track of the spool that was used, and then allow you to search there.

Yes, a dropdown is a good idea to add. I agree it's a bit annoying having to go into each item to delete them.
