### ISSUE TITLE
Not an issue - Really counting upwards?

### ISSUE THREAD

**Issue by PatrickGlatz** [Donkie/Spoolman#2]
Hi @Donkie ,

Just came from the moonraker thread where I found your standalone service. Now I saw, that you have changed to count usage upwards. 

Coming from OctoPrint I was thinking about it, that I like it the most that when Starting a print, octoprint will tell me: Hey your spool doesn't have enough filament for your gcode. If i then resume to print, and it really comes to 0, it just proceeds counting downwards and you have a negative filament amount. But that is like a cross check. I personally are always specifying 20g less then what is specified so to have a buffer. 

I didn't know where I should discuss this, so sorry for the issue. 

One more thing: what do you assume, by when will such a feature be available in moonraker/mainsail ? Filament Manager is the only thing hindering me to switch from octoprint.

Thanks for your great work
Patrick

**Comment by Donkie** [comment]
Hey @PatrickGlatz , glad you found your way in here!

The upwards counting change I made will actually make it more possible to do what you want. This back end fully supports it, and it's up to the front end to display it in such a way to make it negative:
* weight_left = full_weight - used_weight
* Since used_weight can grow in an unbounded fashion now, weight_left will become negative. Then moonraker/mainsail can take action on that and give you a warning if it wants to.

Regarding when this will be available, no clue. I'm still waiting for feedback from Arksine on this approach, whether this is something he envisions moonraker supporting. I can assist with implementing it in Moonraker, but I'd rather have Arksine's blessing before spending any more time on this.

That's the first step, then the clients such as mainsail need to support it as well.

**Comment by PatrickGlatz** [comment]
Hi @Donkie 

thanks so much for the explanation. That makes somehow sense to me. But what i am wondering is, whether the front end then has to maintain also a database with the initial spool weight. Is it then not doubled? Or is full_weight also specified in your database?

If you would need a Beta Tester then in mainsail, i would be raise my hands up.

Thanks for your efforts
Patrick

**Comment by Donkie** [comment]
Yes, full_weight is indirectly set in the Spoolman database. You configure the empty spool weight, and the weight of filament in a full spool.

I've actually started using this solution myself for the last few prints, and it's working great. The biggest crux right now for most users would be to set which spool is the active one, it requires some tinkering until the frontend devs add a proper way of setting it. And they won't do that until my pull request in Moonraker https://github.com/Arksine/moonraker/pull/651 is reviewed and merged.

**Comment by Digityle** [comment]
I've just set up vue.js been messing around with mainsail since you and @jmmcaull have both been on back end, I know little but am learning...
