### ISSUE TITLE
Sorting of "Filament" sorts ID instead

### ISSUE THREAD

**Issue by PatrickGlatz** [Donkie/Spoolman#219]
Hi @Donkie,

love your work here, so fantastic and enriches Mainsail so much! Thanks!

Just a small issue: Sorting column "Filament" in the "Spool" Overview sorts the ID ascending or descending instead of sorting by the Filament Name. In my opinion, sorting should be done based on this column and not refering to a different column (in this case: ID).

Thanks

<img width="423" alt="image" src="https://github.com/Donkie/Spoolman/assets/26554156/09fe1c8c-d74f-4e42-b4d9-17ed2bcf76fa">

**Comment by evgarthub** [comment]
it works for me just fine, I installed it using docker, Version 0.14.0 (286e519)

**Comment by PatrickGlatz** [comment]
@evgarthub That is true for me as well on the "Filament" Tab, there everything works. But on the "Spools" Tab it isn't. I also installed it via docker on rasperry pi, Version 0.13.1 (33b1c4f).

I'll try to update as soon as my print is over and then report back

**Comment by PatrickGlatz** [comment]
Tested it also with 0.14.0 and it is still not sorting correct

**Comment by pdsccode** [comment]
Based on the URL parameters that show when clicking the Filament header in the spools table, It seems to get sorted by Filament ID, which would be based on the order you created the filament a spool is based on.

I suppose this is expected behaviour since the header is called "Filament" though I see the confusion and propose a change as follows:

- Change the header of the column "Filament" to "Name"
- Change the sorting of this column to "Name" instead of ID

What do you think @Donkie?

**Comment by PatrickGlatz** [comment]
@pdsccode 👍

@Donkie : Do you think that can be easily fixed? Thanks.

Seems also to be the case with me. URL after sorting of filament is: http://printpi:7912/spool#sorters=%5B%7B%22field%22%3A%22filament.id%22%2C%22order%22%3A%22asc%22%7D%5D

<img width="1116" alt="image" src="https://github.com/Donkie/Spoolman/assets/26554156/998025f6-ca3f-4f44-97cd-7001f02418f5">
