### ISSUE TITLE
Manually Adjust Spool Usage

### ISSUE THREAD

**Issue by solo2424** [Donkie/Spoolman#30]
Can you add an option to manually adjust spool usage after creating the spool. I find times, I forget to set the active spool before a print. It would be nice to be able to manually make the adjustments after the print.

**Comment by Donkie** [comment]
Good idea!

**Comment by solo2424** [comment]
Looks like the option is there now. Did you add it or was I just not noticing? Also, can this request me closed now?
![image](https://github.com/Donkie/Spoolman/assets/1903450/b2ac86db-d14e-4dc3-b56b-42616dad69dc)

**Comment by Donkie** [comment]
That one has always been there! It is a bit cumbersome though since you need to be careful editing spools which are actively being consumed by a printer, since this value is constantly changing in the background.

The idea here would be to add a button where you can add/subtract weight/length. This would not have the same issue.

**Comment by locki-cz** [comment]
best is add to end print macro this: CLEAR_ACTIVE_SPOOL 
then if you forget add SET_ACTIVE_SPOOL ID=X in slicer filament setting it not affect your last spool
and manualy edit used weight.

;)

**Comment by Hillshum** [comment]
I'll add that perhaps a widget/button for quickly updating the weight maybe also have a checkbox for whether the `last_updated` value should be updated as well
