### ISSUE TITLE
Weight attribute for Filament

### ISSUE THREAD

**Issue by akonkol** [Donkie/Spoolman#36]
Hey there, thank you so much for putting your time into building `Spoolman`! Like others this is a feature I would love to have. 

I'm curious to why the model for `Filament` has an attribute for `weight` and `spool_weight` - seems like this would be better tracked in the `Spool` model.  The same "filament" can come in various quantities or you can have multiple spools of the same filament.

For example:
Matter hackers pro abs comes in 2 spool sizes:
- [1kg](https://www.matterhackers.com/store/l/pro-series-abs/sk/M6A3VYQ9)
- [10 lbs](https://www.matterhackers.com/store/l/pro-series-abs-high-capacity-spools/sk/M0VK69WT)

The work around here would be creating multiple Filament objects for the same filament but with different weights which isn't a huge deal but thought I'd chime in.

Love to see the momentum on this project, lets keep it going!

**Comment by Donkie** [comment]
I designed it so that a filament is connected to a SKU. Different filament weights would have different article numbers (barcodes) so then that would be a bit awkward if we grouped all the weights together.

The downside is as you said, you need multiple filament items for the same "filament", but if you happen to purchase different sizes then you could just prefix the filament name with the spool size or something.

**Comment by akonkol** [comment]
cool got it - ive never paid any attention to barcodes on my filament ;)
