### ISSUE TITLE
Calculate Used amount of Filament from a scale weight

### ISSUE THREAD

**Issue by zacgoodwin** [Donkie/Spoolman#570]
**Is your feature request related to a problem? Please describe.**
When I am updating a spool it has the ability to log how much filament was consumed. This is all well and good when copying the values from the slicer but when a print fails I am left not knowing how much Filament was consumed for it. When I measure the weight of the spool post print failure I need to do the calculation of scale weight - (remaining weight + spool weight) to get the number I put into update the spool. 

This is a ton of mental overhead I'd rather not do. 

**Describe the solution you'd like**
Since Spoolman knows Remaining Weight and Spool Weight already let me just put the number I see in the scale and calculate the total update amount. 

**Describe alternatives you've considered**
Really isn't one short of writing my own plugin which I am a bad programmer so that feels out.

**Comment by rainman19121979** [comment]
If I understood everything correctly, this is already integrated. 

![Screenshot 2024-12-29 081220](https://github.com/user-attachments/assets/c10d0324-5aac-4b3d-a88f-ef8300eaa7aa)

Otherwise, I'm currently working on a DIY scale that communicates directly with Spoolman. 
See here:

[https://github.com/rainman19121979/Spoolman-Scale](url)

**Comment by zacgoodwin** [comment]
Ahh, you understood correctly! Thank you!
