### ISSUE TITLE
Measured weight option

### ISSUE THREAD

**Issue by gpmfuchs** [Donkie/Spoolman#63]
When adding or checking used spools, I weigh them.
It would be nice to have the option to simply insert the measured results (in the edit and create screen of spools) and have the used weight variable update accordingly. 
We already know the weights of empty and full spools in the corresponding filament entry to do this calculation.

**Comment by TomW1605** [comment]
so i had a go at implementing this because i wanted a reason to do some more work with nodejs and react. i got it mostly working but it throughs a console error that seems to not cause any issues but i cant get rid of it. i also ended up having to use a selector so the user has to choose what weight they are putting in otherwise things get messy with what weight to use for calculating the other. its a bit messy but it works, if you want to take a look ill do a PR for it

**Comment by Donkie** [comment]
Yes please make a PR and I can give you some feedback :)

**Comment by TomW1605** [comment]
this one can be closed. not sure why merging didnt close it, i must have done the linking wrong
